use hotel_dbl;
show tables;
SELECT 
    *
FROM
    hotel_rev2020;
SELECT 
    COUNT(reservation_status)
FROM
    hotel_rev2018;


with hotels as 
(select * from hotel_rev2018
union
select * from hotel_rev2019
union
select * from hotel_rev2020)
select * from hotels;

with hotels as 
(select * from hotel_rev2018
union
select * from hotel_rev2019
union
select * from hotel_rev2020)
select (stays_in_weekend_nights + stays_in_week_nights)*adr as revenue from hotels;

-- revenue by year
with hotels as 
(select * from hotel_rev2018
union
select * from hotel_rev2019
union
select * from hotel_rev2020)
select arrival_date_year, (stays_in_weekend_nights + stays_in_week_nights)*adr 
as revenue  from hotels;

-- examine the revenue generated by year in each hotel

with hotels as 
(select * from hotel_rev2018
union
select * from hotel_rev2019
union
select * from hotel_rev2020)
select arrival_date_year, hotel,
round(sum((stays_in_weekend_nights + stays_in_week_nights)*adr), 2)
as revenue  from hotels
group by arrival_date_year, hotel
order by revenue desc;